#!/usr/bin/env python3
"""Builds lib/core/l10n/ru.dart from tool/l10n/*.txt (`uzbek source ||| russian`) and checks coverage.

Usage: python3 tool/l10n/build.py [--check]
Every `tr('…')` call in lib/ must have an entry; enum labels and dictionary strings are listed in extra.txt.
"""
import glob, os, re, sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
SEP = ' ||| '
CALL = re.compile(r"\btr\('((?:[^'\\]|\\.)*)'")
PLACEHOLDER = re.compile(r'\{\w+\}')


def load():
    entries = {}
    for path in sorted(glob.glob(os.path.join(ROOT, 'tool/l10n/*.txt'))):
        for n, line in enumerate(open(path, encoding='utf-8').read().split('\n'), 1):
            if not line.strip() or line.startswith('#'):
                continue
            if SEP not in line:
                sys.exit(f'{path}:{n}: missing separator')
            key, value = line.split(SEP, 1)
            if key in entries and entries[key] != value:
                sys.exit(f'{path}:{n}: conflicting duplicate {key!r}')
            entries[key] = value
    return entries


def code_keys():
    keys = {}
    for f in glob.glob(os.path.join(ROOT, 'lib/**/*.dart'), recursive=True):
        rel = os.path.relpath(f, ROOT)
        if rel.startswith('lib/core/l10n/'):
            continue
        for m in CALL.finditer(open(f, encoding='utf-8').read()):
            keys.setdefault(m.group(1), rel)
    return keys


def dart_string(value):
    return "'" + value.replace("'", "\\'").replace('$', '\\$') + "'"


def main():
    entries = load()
    keys = code_keys()
    problems = []
    for key, rel in sorted(keys.items()):
        if key not in entries:
            problems.append(f'missing: {key!r} ({rel})')
    for key, value in entries.items():
        if sorted(PLACEHOLDER.findall(key)) != sorted(PLACEHOLDER.findall(value)):
            problems.append(f'placeholder mismatch: {key!r} -> {value!r}')
    if '--check' in sys.argv or problems:
        for p in problems:
            print(p)
    out = ["// GENERATED by tool/l10n/build.py from tool/l10n/*.txt — do not edit by hand.",
           "// Russian translations keyed by the Uzbek source text used in the code.",
           "const Map<String, String> russianStrings = {"]
    for key in sorted(entries):
        out.append(f"  {dart_string(key)}: {dart_string(entries[key])},")
    out.append('};')
    open(os.path.join(ROOT, 'lib/core/l10n/ru.dart'), 'w', encoding='utf-8').write('\n'.join(out) + '\n')
    try:  # keep the generated file formatted so `dart format --set-exit-if-changed` stays green
        import subprocess
        subprocess.run(['dart', 'format', os.path.join(ROOT, 'lib/core/l10n/ru.dart')], check=False, capture_output=True)
    except OSError:
        pass
    print(f'{len(entries)} entries, {len(problems)} problems')
    sys.exit(1 if problems else 0)


main()
