import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import { IsEnum, IsOptional, IsString, Length, Matches, MaxLength, ValidateNested } from 'class-validator';

export class RequestOtpDto {
  @ApiProperty({ example: '+998 90 123 45 67' })
  @IsString()
  @MaxLength(32)
  phone!: string;
}

export enum PlatformDto {
  android = 'android',
  ios = 'ios',
  web = 'web',
  other = 'other',
}

export class DeviceDto {
  @ApiProperty({ description: 'Stable per-install identifier generated by the app' })
  @IsString()
  @Length(8, 128)
  id!: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  @MaxLength(120)
  name?: string;

  @ApiProperty({ enum: PlatformDto })
  @IsEnum(PlatformDto)
  platform!: PlatformDto;
}

export class VerifyOtpDto extends RequestOtpDto {
  @ApiProperty({ example: '123456' })
  @Matches(/^\d{6}$/, { message: 'code must be 6 digits' })
  code!: string;

  @ApiProperty({ type: DeviceDto })
  @ValidateNested()
  @Type(() => DeviceDto)
  device!: DeviceDto;
}

export class RefreshDto {
  @ApiProperty()
  @IsString()
  @Length(20, 200)
  refreshToken!: string;
}
